Specify bravado-core version in orc8r setup.py
Summary:
- Only specifying the major version for `bravado-core` causes `AttributeError: module 'jsonschema._validators' has no attribute 'type_draft4'` on `test_type_checking (eventd.tests.event_validation_tests.EventValidationTests)`
- `jsonschema` is also locked as a dependency for a validation error

Reviewed By: tmdzk

Differential Revision: D20261378

fbshipit-source-id: 9086ac2e99beea09abc83527be57f72c1b8915a4