Fix fabfile for packaging GW software with empty hash
Summary:
**Summary**
Users are seeing the following error when following the instruction in https://facebookincubator.github.io/magma/docs/howtos/readme_package to package gateway software.

```
HOST:~/magma/lte/gateway$ fab dev package:git
[localhost] local: pwd
[localhost] local: vagrant status magma
VM magma is not running... Attempting to bring it up.
[localhost] local: vagrant up magma
Bringing machine 'magma' up with 'virtualbox' provider...
==> magma: You assigned a static IP ending in ".1" to this machine.
==> magma: This is very often used by the router and can cause the
==> magma: network to not work properly. If the network doesn't work
==> magma: properly, try changing this IP.
==> magma: You assigned a static IP ending in ".1" to this machine.
==> magma: This is very often used by the router and can cause the
==> magma: network to not work properly. If the network doesn't work
==> magma: properly, try changing this IP.
==> magma: Checking if box 'amarpad/magma_dev' version '1.0.1542061022' is up to date...
==> magma: Resuming suspended VM...
==> magma: Booting VM...
==> magma: Waiting for machine to boot. This may take a few minutes...
    magma: SSH address: 127.0.0.1:2222
    magma: SSH username: vagrant
    magma: SSH auth method: private key
==> magma: Machine booted and ready!
==> magma: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> magma: flag to force provisioning. Provisioners marked to run always will still run.
[localhost] local: vagrant status magma
[localhost] local: vagrant ssh-config magma
[localhost] local: echo "Host magma
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/sraval/Documents/Magma-Docker/magma/lte/gateway/.vagrant/machines/magma/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL" | grep HostName
[localhost] local: echo "Host magma
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/sraval/Documents/Magma-Docker/magma/lte/gateway/.vagrant/machines/magma/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL" | grep Port
[localhost] local: echo "Host magma
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/sraval/Documents/Magma-Docker/magma/lte/gateway/.vagrant/machines/magma/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL" | grep IdentityFile
Building magma package, picking up commit ...
[vagrant@127.0.0.1:2222] run: make clean
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())
[vagrant@127.0.0.1:2222] out: make -C /home/vagrant/magma/lte/gateway/python clean
[vagrant@127.0.0.1:2222] out: make[1]: Entering directory '/home/vagrant/magma/lte/gateway/python'
[vagrant@127.0.0.1:2222] out: make -C /home/vagrant/magma/lte/gateway/python remove_egg
[vagrant@127.0.0.1:2222] out: make[2]: Entering directory '/home/vagrant/magma/lte/gateway/python'
[vagrant@127.0.0.1:2222] out: rm -rf *.egg-info
[vagrant@127.0.0.1:2222] out: make[2]: Leaving directory '/home/vagrant/magma/lte/gateway/python'
[vagrant@127.0.0.1:2222] out: make -C /home/vagrant/magma/orc8r/gateway/python remove_egg
[vagrant@127.0.0.1:2222] out: make[2]: Entering directory '/home/vagrant/magma/orc8r/gateway/python'
[vagrant@127.0.0.1:2222] out: rm -rf *.egg-info
[vagrant@127.0.0.1:2222] out: make[2]: Leaving directory '/home/vagrant/magma/orc8r/gateway/python'
[vagrant@127.0.0.1:2222] out: sudo rm -rf /home/vagrant/build/python/ .coverage
[vagrant@127.0.0.1:2222] out: sudo find . -name '*.pyc' -o -name '__pycache__' -prune -exec rm -rf {} \;
[vagrant@127.0.0.1:2222] out: make[1]: Leaving directory '/home/vagrant/magma/lte/gateway/python'
[vagrant@127.0.0.1:2222] out: rm -rf /home/vagrant/build/c/
[vagrant@127.0.0.1:2222] out:
[vagrant@127.0.0.1:2222] run: ./release/build-magma.sh -h  -t Debug --cert $MAGMA_ROOT/.cache/test_certs/rootCA.pem --proxy $MAGMA_ROOT/lte/gateway/configs/control_proxy.yml
[vagrant@127.0.0.1:2222] out: Error: unknown cmdline option: Debug
[vagrant@127.0.0.1:2222] out: Usage: ./release/build-magma.sh [-v|--version V] [-i|--iteration I] [-h|--hash HASH]
[vagrant@127.0.0.1:2222] out:     [-t|--type Debug|RelWithDebInfo] [-c|--cert <path to cert .pem file>]
[vagrant@127.0.0.1:2222] out:     [-p|--proxy <path to control_proxy config .yml file]>
[vagrant@127.0.0.1:2222] out:
Fatal error: run() received nonzero return code 1 while executing!
Requested: ./release/build-magma.sh -h  -t Debug --cert $MAGMA_ROOT/.cache/test_certs/rootCA.pem --proxy $MAGMA_ROOT/lte/gateway/configs/control_proxy.yml
Executed: /bin/bash -l -c "cd ~/magma/lte/gateway >/dev/null && ./release/build-magma.sh -h  -t Debug --cert \$MAGMA_ROOT/.cache/test_certs/rootCA.pem --proxy \$MAGMA_ROOT/lte/gateway/configs/control_proxy.yml"
Aborting.
Disconnecting from vagrant@127.0.0.1:2222... done.
```

The problem is the `fabfile.py` putting an empty hash after the `-h` option `./release/build-magma.sh -h  -t Debug --cert $MAGMA_ROOT/.cache/test_certs/rootCA.pem --proxy $MAGMA_ROOT/lte/gateway/configs/control_proxy.yml`.
Instead, the command should look like `./release/build-magma.sh -h "" -t Debug --cert $MAGMA_ROOT/.cache/test_certs/rootCA.pem --proxy $MAGMA_ROOT/lte/gateway/configs/control_proxy.yml`

**Implementation**
Add `""` around the hash variable.

**Result**
Now user could follow the instruction to build a gateway package.

Reviewed By: xjtian

Differential Revision: D15329810

fbshipit-source-id: 4f480b6eab64b26635697ed61b7f649034caefd6