Turned on disable_known_hosts fab option. (#190)
Summary:
Effectively turns off StrictHostKeyChecking.

Vagrant guests share the same address on a linux host and StrictHostKeyChecking will fail if running more than one vagrant box.

```
➜  gateway git:(master) ✗ fab dev package:git
...
fabric.exceptions.NetworkError: Host key for 127.0.0.1 did not match pre-existing key! Server's key was changed recently, or possible man-in-the-middle attack.
```
Pull Request resolved: https://github.com/facebookincubator/magma/pull/190

Reviewed By: sciencemanx

Differential Revision: D14991687

Pulled By: xjtian

fbshipit-source-id: c46e649037e5687c362a17c792362f9042ce9d4f