AGW: python: fix eventlet dependency (#6772)
This patch fixes following issue, this is due to most recent release of eventlet.
Lets revert to older release.

======================================================================
ERROR: Failure: ImportError (cannot import name 'ALREADY_HANDLED')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vagrant/build/python/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/vagrant/build/python/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/openflow/tests/test_msg_hub.py", line 18, in <module>
    from magma.pipelined.openflow.messages import MessageHub
  File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/openflow/messages.py", line 17, in <module>
    import ryu.base.app_manager  # pylint: disable=unused-import
  File "/home/vagrant/build/python/lib/python3.5/site-packages/ryu/base/app_manager.py", line 35, in <module>
    from ryu.app import wsgi
  File "/home/vagrant/build/python/lib/python3.5/site-packages/ryu/app/wsgi.py", line 109, in <module>
    class _AlreadyHandledResponse(Response):
  File "/home/vagrant/build/python/lib/python3.5/site-packages/ryu/app/wsgi.py", line 111, in _AlreadyHandledResponse
    from eventlet.wsgi import ALREADY_HANDLED
ImportError: cannot import name 'ALREADY_HANDLED'

Signed-off-by: Pravin B Shelar <pbshelar@fb.com>