Fix milenage unit test
Summary:
the D20096724 introduced a milenage unit test failure

?   	magma/lte/cloud/go	[no test files]
 --- FAIL: TestValidateGenerateSIPAuthVectorInputs (0.00s)
    milenage_test.go:131:
        	Error Trace:	milenage_test.go:131
        	Error:      	Error message not equal:
        	            	expected: "sequence number too large, expected a number which can fit in 48 bits. Got: 140737488355328"
        	            	actual  : "sequence number too large, expected a number which can fit in 48 bits. Got: 281474976710656"
        	Test:       	TestValidateGenerateSIPAuthVectorInputs
 --- FAIL: TestValidateGenerateSIPAuthVectorWithRandInputs (0.00s)
    milenage_test.go:157:
        	Error Trace:	milenage_test.go:157
        	Error:      	Error message not equal:
        	            	expected: "sequence number too large, expected a number which can fit in 48 bits. Got: 140737488355328"
        	            	actual  : "sequence number too large, expected a number which can fit in 48 bits. Got: 281474976710656"
        	Test:       	TestValidateGenerateSIPAuthVectorWithRandInputs

Reviewed By: themarwhal

Differential Revision: D20187168

fbshipit-source-id: 122ef261989f16dec53f0bc28f3e6c1599bcf35a