fix(agw): handle missing error code on service failure
Fixes following exception:
```
magma-dev-focal pipelined[2619]: Traceback (most recent call last):
magma-dev-focal pipelined[2619]:   File "/usr/local/bin/service_util.py", line 80, in <module>
magma-dev-focal pipelined[2619]:     update_stats(service_name)
magma-dev-focal pipelined[2619]:   File "/usr/local/bin/service_util.py", line 69, in update_stats
magma-dev-focal pipelined[2619]:     status = get_status()
magma-dev-focal pipelined[2619]:   File "/usr/local/bin/service_util.py", line 42, in get_status
magma-dev-focal pipelined[2619]:     ServiceExitStatus.ExitCode.Value(exit_code.upper())
magma-dev-focal pipelined[2619]: AttributeError: 'NoneType' object has no attribute 'upper'
```

Signed-off-by: Pravin B Shelar <pbshelar@fb.com>