symphony/circleci: fixing circleci config
Summary:
Fixes the following validation error:
```
~/fbsource/fbcode/fbc/symphony » circleci config validate                                                                                       alexsn@alexsn-mbp
Error: ERROR IN CONFIG FILE:
[#/jobs] 8 schema violations found
Any string key is allowed as job name.
1. [#/jobs/testim] 0 subschemas matched instead of one
|   1. [#/jobs/testim] only 1 subschema matches out of 2
|   |   1. [#/jobs/testim/steps/0] 0 subschemas matched instead of one
|   |   |   1. [#/jobs/testim/steps/0] 0 subschemas matched instead of one
|   |   |   |   1. [#/jobs/testim/steps/0] expected type: String, found: Mapping
|   |   |   |   |   Shorthand commands, like `checkout`
|   |   |   |   |   SCHEMA:
|   |   |   |   |     type: string
|   |   |   |   |   INPUT:
|   |   |   |   |     when:
|   |   |   |   |       condition: <<parameters.before_test>>
|   |   |   |   |       steps: <<parameters.before_test>>
|   |   |   |   2. [#/jobs/testim/steps/0/when] only 1 subschema matches out of 2
|   |   |   |   |   1. [#/jobs/testim/steps/0/when] subject must not be valid against schema {"pattern":"^when$"}
|   |   |   |   |   |   SCHEMA:
|   |   |   |   |   |     not:
|   |   |   |   |   |       pattern: ^when$
|   |   |   |   |   |   INPUT:
|   |   |   |   |   |     condition: <<parameters.before_test>>
|   |   |   |   |   |     steps: <<parameters.before_test>>
|   |   |   2. [#/jobs/testim/steps/0/when/steps] expected type: Sequence, found: String
|   |   |   |   SCHEMA:
|   |   |   |     type: array
|   |   |   |   INPUT:
|   |   |   |     <<parameters.before_test>>
|   2. [#/jobs/testim] expected type: String, found: Mapping
|   |   Job may be a string reference to another job
2. [#/jobs/tfapply] 0 subschemas matched instead of one
|   1. [#/jobs/tfapply] only 1 subschema matches out of 2
|   |   1. [#/jobs/tfapply/steps/2] 0 subschemas matched instead of one
|   |   |   1. [#/jobs/tfapply/steps/2] 0 subschemas matched instead of one
|   |   |   |   1. [#/jobs/tfapply/steps/2] expected type: String, found: Mapping
|   |   |   |   |   Shorthand commands, like `checkout`
|   |   |   |   |   SCHEMA:
|   |   |   |   |     type: string
|   |   |   |   |   INPUT:
|   |   |   |   |     when:
|   |   |   |   |       condition: <<parameters.after_checkout>>
|   |   |   |   |       steps: <<parameters.after_checkout>>
|   |   |   |   2. [#/jobs/tfapply/steps/2/when] only 1 subschema matches out of 2
|   |   |   |   |   1. [#/jobs/tfapply/steps/2/when] subject must not be valid against schema {"pattern":"^when$"}
|   |   |   |   |   |   SCHEMA:
|   |   |   |   |   |     not:
|   |   |   |   |   |       pattern: ^when$
|   |   |   |   |   |   INPUT:
|   |   |   |   |   |     condition: <<parameters.after_checkout>>
|   |   |   |   |   |     steps: <<parameters.after_checkout>>
|   |   |   2. [#/jobs/tfapply/steps/2/when/steps] expected type: Sequence, found: String
|   |   |   |   SCHEMA:
|   |   |   |     type: array
|   |   |   |   INPUT:
|   |   |   |     <<parameters.after_checkout>>
|   2. [#/jobs/tfapply] expected type: String, found: Mapping
|   |   Job may be a string reference to another job
```

Reviewed By: idoshveki

Differential Revision: D21837051

fbshipit-source-id: e5d2f640104e154922ee95bfb192376aac862011