Reset testcase failure fixes (#656)
Summary:
Reset testcase failures  issue fixed in reset test scripts
Issue: Reset testcase were failing with below error message

 reset_req.u = s1ap_types.U()
TypeError: incompatible types, U instance instead of U instance

verified by: s1ap-tester
Pull Request resolved: https://github.com/facebookincubator/magma/pull/656

Reviewed By: ssanadhya

Differential Revision: D18044263

Pulled By: emakeev

fbshipit-source-id: 89049bb45e0f0c3e6f9c3c697486b1238bef3333