Fix the path of test certs for api host (#1721)
Summary:
The following ERROR occurs when testing with docker-compose for symphony.

  ERROR: for magmalte Cannot create container for service magmalte: invalid mount config
               for type "bind": bind source path does not exist:
                 /magma/symphony/.cache/test_certs/admin_operator.pem

Therefore, I fixed the correct path to test_certs (/magma/.cache/test_certs/admin_operator.pem).
Pull Request resolved: https://github.com/facebookincubator/magma/pull/1721

Reviewed By: themarwhal

Differential Revision: D21746735

Pulled By: xjtian

fbshipit-source-id: eeb6a9033112ae4cfa8311a02d6121531cdc3a53